/* Autogenerated file, do not edit */

#include <stdint.h>
#include <stdbool.h>
#include "avr_op_decoder.h"

static const char *instr_names[] =
{
    "undefined",
    "bclr",
    "bset",
    "icall",
    "ijmp",
    "lpm_r0",
    "lpm",
    "lpm_inc",
    "nop",
    "wdr",
    "ret",
    "adc",
    "add",
    "and",
    "cp",
    "cpc",
    "cpse",
    "eor",
    "mov",
    "mul",
    "or",
    "sbc",
    "sub",
    "andi",
    "ldi",
    "ori",
    "cpi",
    "sbci",
    "subi",
    "sbrc",
    "sbrs",
    "bld",
    "bst",
    "in",
    "out",
    "adiw",
    "sbiw",
    "cbi",
    "sbi",
    "sbic",
    "sbis",
    "brbc",
    "brbs",
    "rcall",
    "rjmp",
    "call",
    "jmp",
    "asr",
    "com",
    "dec",
    "inc",
    "lsr",
    "neg",
    "pop",
    "push",
    "ror",
    "swap",
    "movw",
    "sts",
    "lds",
    "ld_x",
    "ld_x_inc",
    "ld_x_dec",
    "ld_y_inc",
    "ld_y_dec",
    "ldd_y",
    "ld_z_inc",
    "ld_z_dec",
    "ldd_z",
    "st_x",
    "st_x_inc",
    "st_x_dec",
    "st_y_inc",
    "st_y_dec",
    "std_y",
    "st_z_inc",
    "st_z_dec",
    "std_z",
    "muls",
    "mulsu",
    "fmul",
    "fmuls",
    "fmulsu",
    "sleep",
    "break",
};

//--- instruction name getters
const char *avr_get_instr_name_by_id(avr_instr_t id)
{
    if (id < 85)
        return instr_names[id];
    return "?";
}

//--- instruction decoders
static void decode_undefined(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_bclr(avr_operands_t *result, uint16_t opcode)
{
    result->bit = ((opcode & 0x0070) >> 4);
}

static void decode_bset(avr_operands_t *result, uint16_t opcode)
{
    result->bit = ((opcode & 0x0070) >> 4);
}

static void decode_icall(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_ijmp(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_lpm_r0(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_lpm(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_lpm_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_nop(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_wdr(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_ret(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_adc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_add(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_and(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_cp(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_cpc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_cpse(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_eor(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_mov(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_mul(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_or(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_sbc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_sub(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0) | ((opcode & 0x0200) >> 5);
}

static void decode_andi(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_ldi(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_ori(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_cpi(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_sbci(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_subi(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x0f00) >> 4);
}

static void decode_sbrc(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_sbrs(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_bld(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_bst(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_in(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x000f) >> 0) | ((opcode & 0x0600) >> 5);
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_out(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x000f) >> 0) | ((opcode & 0x0600) >> 5);
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_adiw(avr_operands_t *result, uint16_t opcode)
{
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x00c0) >> 2);
    result->rd = ((opcode & 0x0030) >> 4);
    result->rd += 12;
}

static void decode_sbiw(avr_operands_t *result, uint16_t opcode)
{
    result->imm = ((opcode & 0x000f) >> 0) | ((opcode & 0x00c0) >> 2);
    result->rd = ((opcode & 0x0030) >> 4);
    result->rd += 12;
}

static void decode_cbi(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x00f8) >> 3);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_sbi(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x00f8) >> 3);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_sbic(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x00f8) >> 3);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_sbis(avr_operands_t *result, uint16_t opcode)
{
    result->port = ((opcode & 0x00f8) >> 3);
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_brbc(avr_operands_t *result, uint16_t opcode)
{
    result->pc_offset = ((opcode & 0x03f8) >> 3);
    result->pc_offset = ((int) result->pc_offset << 25) >> 25;
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_brbs(avr_operands_t *result, uint16_t opcode)
{
    result->pc_offset = ((opcode & 0x03f8) >> 3);
    result->pc_offset = ((int) result->pc_offset << 25) >> 25;
    result->bit = ((opcode & 0x0007) >> 0);
}

static void decode_rcall(avr_operands_t *result, uint16_t opcode)
{
    result->pc_offset = ((opcode & 0x0fff) >> 0);
    result->pc_offset = ((int) result->pc_offset << 20) >> 20;
}

static void decode_rjmp(avr_operands_t *result, uint16_t opcode)
{
    result->pc_offset = ((opcode & 0x0fff) >> 0);
    result->pc_offset = ((int) result->pc_offset << 20) >> 20;
}

static void decode_call(avr_operands_t *result, uint16_t opcode)
{
    result->addr_msbyte = ((opcode & 0x0001) >> 0) | ((opcode & 0x01f0) >> 3);
}

static void decode_jmp(avr_operands_t *result, uint16_t opcode)
{
    result->addr_msbyte = ((opcode & 0x0001) >> 0) | ((opcode & 0x01f0) >> 3);
}

static void decode_asr(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_com(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_lsr(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_neg(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_pop(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_push(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_ror(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_swap(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_movw(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rr = ((opcode & 0x000f) >> 0);
}

static void decode_sts(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_lds(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_x(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_x_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_x_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_y_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_y_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ldd_y(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->ptr_displacement = ((opcode & 0x0007) >> 0) | ((opcode & 0x0c00) >> 7) | ((opcode & 0x2000) >> 8);
}

static void decode_ld_z_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ld_z_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
}

static void decode_ldd_z(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x01f0) >> 4);
    result->ptr_displacement = ((opcode & 0x0007) >> 0) | ((opcode & 0x0c00) >> 7) | ((opcode & 0x2000) >> 8);
}

static void decode_st_x(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_x_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_x_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_y_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_y_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_std_y(avr_operands_t *result, uint16_t opcode)
{
    result->ptr_displacement = ((opcode & 0x0007) >> 0) | ((opcode & 0x0c00) >> 7) | ((opcode & 0x2000) >> 8);
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_z_inc(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_st_z_dec(avr_operands_t *result, uint16_t opcode)
{
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_std_z(avr_operands_t *result, uint16_t opcode)
{
    result->ptr_displacement = ((opcode & 0x0007) >> 0) | ((opcode & 0x0c00) >> 7) | ((opcode & 0x2000) >> 8);
    result->rr = ((opcode & 0x01f0) >> 4);
}

static void decode_muls(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x00f0) >> 4);
    result->rd += 16;
    result->rr = ((opcode & 0x000f) >> 0);
    result->rr += 16;
}

static void decode_mulsu(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x0070) >> 4);
    result->rd += 16;
    result->rr = ((opcode & 0x0007) >> 0);
    result->rr += 16;
}

static void decode_fmul(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x0070) >> 4);
    result->rd += 16;
    result->rr = ((opcode & 0x0007) >> 0);
    result->rr += 16;
}

static void decode_fmuls(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x0070) >> 4);
    result->rd += 16;
    result->rr = ((opcode & 0x0007) >> 0);
    result->rr += 16;
}

static void decode_fmulsu(avr_operands_t *result, uint16_t opcode)
{
    result->rd = ((opcode & 0x0070) >> 4);
    result->rd += 16;
    result->rr = ((opcode & 0x0007) >> 0);
    result->rr += 16;
}

static void decode_sleep(avr_operands_t *result, uint16_t opcode)
{
}

static void decode_break(avr_operands_t *result, uint16_t opcode)
{
}


//--- instruction matcher
avr_instr_t avr_decode(avr_operands_t *result, uint16_t op)
{
    static void (* const unpackers[85])(avr_operands_t *, uint16_t) =
    {
        decode_undefined,
        decode_bclr, decode_bset, decode_icall, decode_ijmp, decode_lpm_r0, decode_lpm, decode_lpm_inc, decode_nop, 
        decode_wdr, decode_ret, decode_adc, decode_add, decode_and, decode_cp, decode_cpc, decode_cpse, 
        decode_eor, decode_mov, decode_mul, decode_or, decode_sbc, decode_sub, decode_andi, decode_ldi, 
        decode_ori, decode_cpi, decode_sbci, decode_subi, decode_sbrc, decode_sbrs, decode_bld, decode_bst, 
        decode_in, decode_out, decode_adiw, decode_sbiw, decode_cbi, decode_sbi, decode_sbic, decode_sbis, 
        decode_brbc, decode_brbs, decode_rcall, decode_rjmp, decode_call, decode_jmp, decode_asr, decode_com, 
        decode_dec, decode_inc, decode_lsr, decode_neg, decode_pop, decode_push, decode_ror, decode_swap, 
        decode_movw, decode_sts, decode_lds, decode_ld_x, decode_ld_x_inc, decode_ld_x_dec, decode_ld_y_inc, decode_ld_y_dec, 
        decode_ldd_y, decode_ld_z_inc, decode_ld_z_dec, decode_ldd_z, decode_st_x, decode_st_x_inc, decode_st_x_dec, decode_st_y_inc, 
        decode_st_y_dec, decode_std_y, decode_st_z_inc, decode_st_z_dec, decode_std_z, decode_muls, decode_mulsu, decode_fmul, 
        decode_fmuls, decode_fmulsu, decode_sleep, decode_break, 
    };

    static const uint8_t lut0[2048] =
    {
        0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 
        3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
        9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
        11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
        12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
        14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 
        15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 
        16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
        16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
        25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
        26, 27, 27, 27, 28, 28, 28, 28, 29, 30, 30, 30, 31, 32, 33, 30, 
        34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 
        36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 
        38, 38, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 
        40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
        40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
        23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
        41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
        41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
        41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
        41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
        42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 
        42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 
        42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 
        42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 
        46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 
        47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 
        47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 
        48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 
        49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 
        50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
        51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 
    };

    static const uint8_t lut1[52][32] =
    {
        { 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        { 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57},
        { 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78},
        { 79, 79, 79, 79, 79, 79, 79, 79, 80, 80, 80, 80, 80, 80, 80, 80, 79, 79, 79, 79, 79, 79, 79, 79, 80, 80, 80, 80, 80, 80, 80, 80},
        { 81, 81, 81, 81, 81, 81, 81, 81, 82, 82, 82, 82, 82, 82, 82, 82, 81, 81, 81, 81, 81, 81, 81, 81, 82, 82, 82, 82, 82, 82, 82, 82},
        { 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15},
        { 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21},
        { 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12},
        { 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16},
        { 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14},
        { 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22},
        { 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11},
        { 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13},
        { 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17},
        { 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20},
        { 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18},
        { 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26},
        { 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27},
        { 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28},
        { 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25},
        { 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23},
        { 68, 68, 68, 68, 68, 68, 68, 68, 65, 65, 65, 65, 65, 65, 65, 65, 68, 68, 68, 68, 68, 68, 68, 68, 65, 65, 65, 65, 65, 65, 65, 65},
        { 77, 77, 77, 77, 77, 77, 77, 77, 74, 74, 74, 74, 74, 74, 74, 74, 77, 77, 77, 77, 77, 77, 77, 77, 74, 74, 74, 74, 74, 74, 74, 74},
        { 59, 66, 67, 0, 6, 7, 0, 0, 0, 63, 64, 0, 60, 61, 62, 53, 59, 66, 67, 0, 6, 7, 0, 0, 0, 63, 64, 0, 60, 61, 62, 53},
        { 58, 75, 76, 0, 0, 0, 0, 0, 0, 72, 73, 0, 69, 70, 71, 54, 58, 75, 76, 0, 0, 0, 0, 0, 0, 72, 73, 0, 69, 70, 71, 54},
        { 48, 52, 56, 50, 0, 47, 51, 55, 2, 4, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 2, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 2, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 2, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 1, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 1, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 10, 3, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 0, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 0, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 0, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 83, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 84, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 9, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 0, 0, 49, 0, 46, 46, 45, 45},
        { 48, 52, 56, 50, 0, 47, 51, 55, 5, 0, 49, 0, 46, 46, 45, 45, 48, 52, 56, 50, 0, 47, 51, 55, 0, 0, 49, 0, 46, 46, 45, 45},
        { 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35},
        { 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36},
        { 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37},
        { 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39},
        { 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38},
        { 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40},
        { 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19},
        { 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33},
        { 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34},
        { 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44},
        { 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43},
        { 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24},
        { 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42},
        { 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41},
        { 31, 31, 31, 31, 31, 31, 31, 31, 0, 0, 0, 0, 0, 0, 0, 0, 31, 31, 31, 31, 31, 31, 31, 31, 0, 0, 0, 0, 0, 0, 0, 0},
        { 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0, 32, 32, 32, 32, 32, 32, 32, 32, 0, 0, 0, 0, 0, 0, 0, 0},
        { 29, 29, 29, 29, 29, 29, 29, 29, 0, 0, 0, 0, 0, 0, 0, 0, 29, 29, 29, 29, 29, 29, 29, 29, 0, 0, 0, 0, 0, 0, 0, 0},
        { 30, 30, 30, 30, 30, 30, 30, 30, 0, 0, 0, 0, 0, 0, 0, 0, 30, 30, 30, 30, 30, 30, 30, 30, 0, 0, 0, 0, 0, 0, 0, 0},
    };

    int hash = lut0[op >> 5];
    int instr = lut1[hash][op & 0x1F];
    if (result)
        unpackers[instr](result, op);
    return instr;
}
